language: nix
branches:
  only:
  - master
  - production

before_install:
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
    openssl aes-256-cbc -K $encrypted_88bda2ae685f_key -iv $encrypted_88bda2ae685f_iv -in deploy_rsa.enc -out deploy_rsa -d;
    eval "$(ssh-agent -s)";
    chmod 600 $TRAVIS_BUILD_DIR/deploy_rsa;
    ssh-add $TRAVIS_BUILD_DIR/deploy_rsa;
  fi

script:
- if [ "$TRAVIS_PULL_REQUEST" = "false" -a "$TRAVIS_BRANCH" = "master" ]; then
    echo "SITEURL = 'http://weekly.nixos.org'" >> pelicanconf.py;
    echo "WITH_FUTURE_DATES = True" >> pelicanconf.py;
  fi
- nix-build -Q default.nix;

after_success:
- env
- git clone git@github.com:NixOS/nixos-weekly.git gh-pages -b gh-pages
- if [ "$TRAVIS_PULL_REQUEST" = "false" -a "$TRAVIS_BRANCH" = "master" ]; then
    mkdir -p gh-pages/preview;
    rm -rf gh-pages/preview/*;
    cp -RL result/* gh-pages/preview/;
    cd gh-pages;
    git add .;
    if [[ -n `git diff --cached --exit-code` ]]; then
      echo "= git status =============================================";
      git status;
      echo "= git commit =============================================";
      git config user.name 'NixOS Weekly Robot';
      git config user.email 'weekly@nixos.org';
      git commit -a -m "Preview of '$TRAVIS_COMMIT' commit built by Travis-CI \\#$((TRAVIS_JOB_ID - 1))";
      git push git@github.com:NixOS/nixos-weekly.git HEAD:gh-pages;
    else
      echo "==========================================================";
      echo "No changes. Nothing to commit";
      echo "==========================================================";
    fi
  fi;
- if [ "$TRAVIS_PULL_REQUEST" = "false" -a "$TRAVIS_BRANCH" = "production" ]; then
    mv gh-pages/preview tmp-preview;
    mv gh-pages/CNAME tmp-CNAME;
    rm -rf gh-pages/*;
    cp -RL result/* gh-pages/;
    mv tmp-preview gh-pages/preview;
    mv tmp-CNAME gh-pages/CNAME;
    cd gh-pages;
    touch .nojekyll;
    git add .;
    if [[ -n `git diff --cached --exit-code` ]]; then
      echo "= git status =============================================";
      git status;
      echo "= git commit =============================================";
      git config user.name "NixOS Weekly Robot";
      git config user.email "weekly@nixos.org";
      git commit -a -m "Release of $TRAVIS_TAG (commit '$TRAVIS_COMMIT') built by Travis-CI \\#$((TRAVIS_JOB_ID - 1))";
      git push git@github.com:NixOS/nixos-weekly.git HEAD:gh-pages;
    else
      echo "==========================================================";
      echo "No changes. Nothing to commit";
      echo "==========================================================";
    fi
  fi;
