language: nix
branches:
  only:
  - master
  - /^2016-*$/
  - /^2017-*$/
  - /^2018-*$/
script:
- if [ "$TRAVIS_PULL_REQUEST" = "false" -a "$TRAVIS_BRANCH" = "master" ]; then
    nix-build default.nix --argstr current_timestamp "`date -u +%Y-%m-%dT%TZ`" --argstr siteUrl "http://weekly.nixos.org/preview" -o result;
  fi
- if [ "$TRAVIS_TAG" != "" ]; then
    nix-build default.nix --argstr current_timestamp "`date -u +%Y-%m-%dT%TZ`" --argstr siteUrl "http://weekly.nixos.org" -o result;
  fi

before_install:
- openssl aes-256-cbc -K $encrypted_88bda2ae685f_key -iv $encrypted_88bda2ae685f_iv -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 $TRAVIS_BUILD_DIR/deploy_rsa
- ssh-add $TRAVIS_BUILD_DIR/deploy_rsa

after_success:
- env
- git clone git@github.com:NixOS/nixos-weekly.git gh-pages -b gh-pages
- if [ "$TRAVIS_PULL_REQUEST" = "false" -a "$TRAVIS_BRANCH" = "master" ]; then
    mkdir -p gh-pages/preview;
    rm -rf gh-pages/preview/*;
    cp -RL result/* gh-pages/preview/;
    COMMIT_MSG="Preview of '$TRAVIS_COMMIT' commit built by Travis-CI \\#$((TRAVIS_JOB_ID - 1))"
    cd gh-pages;
    git add .;
    if [[ -n `git diff --cached --exit-code` ]]; then
      echo "= git status =============================================";
      git status;
      echo "= git commit =============================================";
      git config user.name 'NixOS Weekly Robot';
      git config user.email 'weekly@nixos.org';
      git commit -a -m "$COMMIT_MSG";
      git push git@github.com:NixOS/nixos-weekly.git HEAD:gh-pages;
    else
      echo "==========================================================";
      echo "No changes. Nothing to commit";
      echo "==========================================================";
    fi
  fi;
- if [ "$TRAVIS_TAG" != "" ]; then
    mv gh-pages/preview tmp-preview;
    rm -rf gh-pages/*;
    cp -RL result/* gh-pages/;
    mv tmp-preview gh-pages/preview;
    COMMIT_MSG="Release of $TRAVIS_TAG (commit '$TRAVIS_COMMIT') built by Travis-CI \\#$((TRAVIS_JOB_ID - 1))"
    cd gh-pages;
    git add .;
    if [[ -n `git diff --cached --exit-code` ]]; then
      echo "= git status =============================================";
      git status;
      echo "= git commit =============================================";
      git config user.name 'NixOS Weekly Robot';
      git config user.email 'weekly@nixos.org';
      git commit -a -m "$COMMIT_MSG";
      git push git@github.com:NixOS/nixos-weekly.git HEAD:gh-pages;
    else
      echo "==========================================================";
      echo "No changes. Nothing to commit";
      echo "==========================================================";
    fi
  fi;
